[options]

  vimcompatible = true
  default_indent = 2
  expand_tab = true

  relativenumber = "nil"
  colorcolumn = 80
  nuw = 10 
  terminal_cursor_shape = 1

  # Set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme layer
  #colorscheme_bg = "light"
  #colorscheme = "molokai"
  # colorscheme = "desert"
  colorscheme = "gruvbox"
  enable_guicolors = true

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  statusline_unicode = true
  
  # windows
  windows_leader = '<F1>'
  windows_smartclose = ''

  # filemanater
  # filemanager = "nerdtree"
  filetree_direction = 'left'
  enable_filetree_filetypeicon = true
  enable_vimfiler_welcome = true

  # custom
  bootstrap_before = 'myspacevim#before'
  bootstrap_after  = 'myspacevim#after'

  #disabled_plutings = ["neomake.vim"]

[[layers]]
  name = "core"
  enable_filetree_gitstatus = true

[[layers]]
  name = "checkers"
  lint_on_the_fly = false
  lint_on_save = true
  open_error_list = 1
  show_cursor_error = false

[[layers]]
  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
# This is a basic configuration example for SpaceVim

[[layers]]
  name = "ui"
  enable_scrollbar = true
  enable_sidebar = true
  enable_indentline = true
  enable_cursorword = true
  conceallevel = 0

#[[layers]]
  #name = "incsearch"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#python"
  format_on_save = true
  enable_linters = ['python', 'pylint']

[[layers]]
  name = "git"

[[layers]]
  name = "ui"
  enable_sidebar = true
  enable_scrollbar = true
  enable_indentline = true
  enable_cursorword = false
  concealcursor = true
  conceallevel = 1
  cursor_delay = 20

[[layers]]
  name = "lang#reason"

[[layers]]
  name = "lsp"
  enabled_clients = ['ocamllsp', 'pyright']

  [layers.override_cmd]
    ocaml = ["ocamllsp"]

